# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a manifest file that contains
# one row per sample. It can be parsed easily via pandas.
cram_manifest: "config/manifest_cram.tsv"
gvcf_manifest: "config/manifest_gvcf.tsv"
sample-logbook: "resources/example_logbook.xlsx.xlsx"
sample-linking:
    sex: "config/sample_linking_sex.tsv"
    external-ids: "config/sample_linking_external_ids.tsv"
data-model: "resources/PMGRC Data Model Conversion - GREGoR Submission.xlsx"
multiqc-config: "config/multiqc_config.yaml"
genome-build: "grch38"
behaviors:
  symlink-crams: yes

references:
  grch38:
    fasta: "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
    exclusion-regions-bed: "resources/grch38_encodelist_centromeres_telomeres.bed"
    genes-gff3-gz: "https://ftp.ensembl.org/pub/current_gff3/homo_sapiens/Homo_sapiens.GRCh38.109.gff3.gz"

somalier:
  grch37:
    sites-vcf-gz: "https://github.com/brentp/somalier/files/3412455/sites.GRCh37.vcf.gz"
    kg-labels-tsv: "https://raw.githubusercontent.com/brentp/somalier/master/scripts/ancestry-labels-1kg.tsv"
    kg-reference-data-tar-gz: "https://zenodo.org/record/3479773/files/1kg.somalier.tar.gz"
  grch38:
    sites-vcf-gz: "https://github.com/brentp/somalier/files/3412456/sites.hg38.vcf.gz"
    kg-labels-tsv: "https://raw.githubusercontent.com/brentp/somalier/master/scripts/ancestry-labels-1kg.tsv"
    kg-reference-data-tar-gz: "https://zenodo.org/record/3479773/files/1kg.somalier.tar.gz"
expansionhunter:
  aligner: "dag-aligner"
  region-extension-length: 1000
  excluded-samples: "config/expansionhunter_excluded_samples.tsv"
expansionhunter_denovo:
  version: "v0.9.0"
  affected-status: "config/affected_status.tsv"
  excluded-samples: "config/expansionhunter_denovo_excluded_samples.tsv"
  annovar-tarball: "resources/annovar.latest.tar.gz"
  plot-locus-count: 10
cyrius:
  version: "v1.1.1"
  excluded-samples: "config/cyrius_excluded_samples.tsv"
glnexus:
  version: "1.4.1"
  config: "DeepVariant_unfiltered"
  calling-ranges: "resources/glnexus_calling_ranges.tsv"
deeptrio:
  docker-version: "deeptrio-1.5.0"
  number-shards: 16
  grch38:
    calling-ranges: "resources/deeptrio_calling_ranges_grch38.tsv"
slivar:
  functions-js: "https://raw.githubusercontent.com/brentp/slivar/master/js/slivar-functions.js"
  affected-status-tsv: "config/affected_status.tsv"
  grch38:
    gnomad-zip: "https://slivar.s3.amazonaws.com/gnomad.hg38.genomes.v3.fix.zip"
    topmed-zip: "https://slivar.s3.amazonaws.com/topmed.hg38.dbsnp.151.zip"
    low-complexity-bed-gz: "https://github.com/lh3/varcmp/raw/master/scripts/LCR-hs38.bed.gz"
