queues:
  small:
    - "small"
  large:
    - "large"
    - "large"

tmpdir: "temp"

default:
  threads: 1
  memory: 2000
  queue: "small"
awscli:
  threads: 1
  memory: 2000
  queue: "small"
bcftools:
  threads: 4
  memory: 8000
  queue: "small"
bedtools:
  threads: 1
  memory: 2000
  queue: "small"
deeptrio:
  threads: 16
  make_examples_memory: 384000
  call_variants_memory: 480000
  postprocess_variants_memory: 32000
  queue: "large"
glnexus:
  threads: 4
  memory: 128000
  queue: "large"
r:
  threads: 1
  memory: 4000
  queue: "small"
samtools:
  threads: 4
  memory: 8000
  queue: "small"
somalier:
  threads: 1
  memory: 1000
  queue: "small"
