$schema: "https://json-schema.org/draft/2020-12/schema"
description: global configuration
properties:
  bam_manifest:
    type: string
  gvcf_manifest:
    type: string
  sample-logbook:
    type: string
  data-model:
    type: string
  multiqc-config:
    type: string
  genome-build:
    type: string
    pattern: "^grch[0-9]+$"
  tmpdir:
    type: string
  behaviors:
    type: object
    properties:
      symlink-bams:
        type: boolean
    required:
      - symlink-bams
    additionalProperties: no
  references:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          fasta:
            type: string
          exclusion-regions-bed:
            type: string
        required:
          - fasta
          - exclusion-regions-bed
        additionalProperties: no
    required:
      - grch38
  somalier:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          sites-vcf-gz:
            type: string
          kg-labels-tsv:
            type: string
          kg-reference-data-tar-gz:
            type: string
        required:
          - sites-vcf-gz
          - kg-labels-tsv
          - kg-reference-data-tar-gz
        additionalProperties: no
  expansionhunter_denovo:
    type: object
    properties:
      repo:
        type: string
    required:
      - repo
    additionalProperties: no
  glnexus:
    type: object
    properties:
      version:
        type: string
      config:
        type: string
      calling-ranges:
        type: string
    required:
      - version
      - config
      - calling-ranges
    additionalProperties: no
  deeptrio:
    type: object
    properties:
      docker-version:
        type: string
      number-shards:
        type: integer
        min: 1
    patternProperties:
      "^grch.*$":
        type: object
        properties:
          calling-ranges:
            type: string
        required:
          - calling-ranges
        additionalProperties: no
    required:
      - docker-version
      - number-shards
      - grch38
    additionalProperties: no
required:
  - bam_manifest
  - gvcf_manifest
  - sample-logbook
  - multiqc-config
  - genome-build
  - tmpdir
  - behaviors
  - references
  - somalier
  - expansionhunter_denovo
  - glnexus
  - deeptrio
additionalProperties: no
