$schema: "https://json-schema.org/draft/2020-12/schema"
description: global configuration
properties:
  bam_manifest:
    type: string
  gvcf_manifest:
    type: string
  sample-logbook:
    type: string
  sample-linking:
    type: object
    properties:
      sex:
        type: string
      external-ids:
        type: string
    additionalProperties: false
  data-model:
    type: string
  multiqc-config:
    type: string
  genome-build:
    type: string
    pattern: "^grch[0-9]+$"
  behaviors:
    type: object
    properties:
      symlink-bams:
        type: boolean
    required:
      - symlink-bams
    additionalProperties: no
  references:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          fasta:
            type: string
          exclusion-regions-bed:
            type: string
          genes-gff3-gz:
            type: string
        required:
          - fasta
          - exclusion-regions-bed
          - genes-gff3-gz
        additionalProperties: no
    required:
      - grch38
  somalier:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          sites-vcf-gz:
            type: string
          kg-labels-tsv:
            type: string
          kg-reference-data-tar-gz:
            type: string
        required:
          - sites-vcf-gz
          - kg-labels-tsv
          - kg-reference-data-tar-gz
        additionalProperties: no
  expansionhunter_denovo:
    type: object
    properties:
      affected-status:
        type: string
      repo:
        type: string
    required:
      - repo
      - affected-status
    additionalProperties: no
  glnexus:
    type: object
    properties:
      version:
        type: string
      config:
        type: string
      calling-ranges:
        type: string
    required:
      - version
      - config
      - calling-ranges
    additionalProperties: no
  deeptrio:
    type: object
    properties:
      docker-version:
        type: string
      number-shards:
        type: integer
        min: 1
    patternProperties:
      "^grch.*$":
        type: object
        properties:
          calling-ranges:
            type: string
        required:
          - calling-ranges
        additionalProperties: no
    required:
      - docker-version
      - number-shards
      - grch38
    additionalProperties: no
  slivar:
    type: object
    properties:
      functions-js:
        type: string
      affected-status-tsv:
        type: string
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          gnomad-zip:
            type: string
          topmed-zip:
            type: string
          low-complexity-bed-gz:
            type: string
        required:
          - gnomad-zip
          - low-complexity-bed-gz
    required:
      - functions-js
      - affected-status-tsv
      - grch38
    additionalProperties: no
required:
  - bam_manifest
  - gvcf_manifest
  - sample-logbook
  - sample-linking
  - multiqc-config
  - genome-build
  - behaviors
  - references
  - somalier
  - expansionhunter_denovo
  - glnexus
  - deeptrio
additionalProperties: no
