$schema: "https://json-schema.org/draft/2020-12/schema"
description: global configuration
properties:
  reads_manifest:
    type: string
  gvcf_manifest:
    type: string
  sample-sex:
    type: string
  data-model:
    type: string
  multiqc-config:
    type: string
  genome-build:
    type: string
    pattern: "^grch[0-9]+$"
  behaviors:
    type: object
    properties:
      symlink-reads:
        type: boolean
    required:
      - symlink-reads
    additionalProperties: no
  references:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          fasta:
            type: string
          exclusion-regions-bed:
            type: string
          genes-gff3-gz:
            type: string
        required:
          - fasta
          - exclusion-regions-bed
          - genes-gff3-gz
        additionalProperties: no
    required:
      - grch38
  somalier:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          sites-vcf-gz:
            type: string
          kg-labels-tsv:
            type: string
          kg-reference-data-tar-gz:
            type: string
        required:
          - sites-vcf-gz
          - kg-labels-tsv
          - kg-reference-data-tar-gz
        additionalProperties: no
  expansionhunter:
    type: object
    properties:
      aligner:
        type: string
        pattern: "^dag-aligner$|^path-aligner$"
      region-extension-length:
        type: integer
        min: 0
      excluded-samples:
        type: string
    required:
      - aligner
      - region-extension-length
      - excluded-samples
    additionalProperties: no
  expansionhunter_denovo:
    type: object
    properties:
      version:
        type: string
      affected-status:
        type: string
      excluded-samples:
        type: string
      annovar-tarball:
        type: string
      plot-locus-count:
        type: integer
        min: 1
    required:
      - version
      - affected-status
      - excluded-samples
    additionalProperties: no
  cyrius:
    type: object
    properties:
      version:
        type: string
      excluded-samples:
        type: string
    required:
      - version
      - excluded-samples
    additionalProperties: no
  glnexus:
    type: object
    properties:
      version:
        type: string
      config:
        type: string
      calling-ranges:
        type: string
    required:
      - version
      - config
      - calling-ranges
    additionalProperties: no
  deeptrio:
    type: object
    properties:
      docker-version:
        type: string
      number-shards:
        type: integer
        min: 1
    patternProperties:
      "^grch.*$":
        type: object
        properties:
          calling-ranges:
            type: string
        required:
          - calling-ranges
        additionalProperties: no
    required:
      - docker-version
      - number-shards
      - grch38
    additionalProperties: no
  slivar:
    type: object
    properties:
      functions-js:
        type: string
      affected-status-tsv:
        type: string
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          gnomad-zip:
            type: string
          topmed-zip:
            type: string
          low-complexity-bed-gz:
            type: string
        required:
          - gnomad-zip
          - low-complexity-bed-gz
    required:
      - functions-js
      - affected-status-tsv
      - grch38
    additionalProperties: no
required:
  - reads_manifest
  - gvcf_manifest
  - sample-sex
  - multiqc-config
  - genome-build
  - behaviors
  - references
  - somalier
  - expansionhunter
  - expansionhunter_denovo
  - cyrius
  - glnexus
  - deeptrio
additionalProperties: no
